### ISSUE TITLE
Update to Revit 19

### ISSUE THREAD

**Issue by thomasoestgulen** [jeremytammik/the_building_coder_samples#9]
Hi Jeremy. Would it be possible to update the VisualStudioRevitAddinWizard for Revit 2019 and Windows 10? I tried to do this my self, but could not get it to work. The Zip for Windows utility is not updated for Windows 10.

**Comment by jeremytammik** [comment]
Why do you raise this issue here, in The Building Coder Samples, and not in the VisualStudioRevitAddinWizard repo? 

https://github.com/jeremytammik/VisualStudioRevitAddinWizard

Furthermore, the wizards have already been updated for Revit 2019, several times over, so the current release is 2019.0.0.4:

https://github.com/jeremytammik/VisualStudioRevitAddinWizard/releases/tag/2019.0.0.4

Please check out the current release and raise a new issue in the correct repo if you still have problems.

Better still, if you encounter a problem, fix it (it is easy) and submit a pull request for me to integrate your fix.

Thank you!
